### ISSUE TITLE
Board definitions - external location?

### ISSUE THREAD

**Issue by 0xc0170** [0xc0170/project_generator#67]
In the #52, it was proposed by @aethaniel , to have board definitions outside of the project_generator. Or at least to be able to pass the yaml record with board definitions for a project, then use that information internally to get the right information.

```
    board_def = {
        # Freescale FRDM boards
        'frdm-k20d50m': {
            'uvision': 'MK20DX128xxx5',
            'gcc' : 'cortex-m4',
        },
        'frdm-kl25z' : {
            'iar' : 'MKL25Z128xxx4',
            'gcc' : 'cortex-m0+',
        },
        'frdm-k64f' : {
            'uvision' : 'MK64FN1M0xxx12',
            'gcc' : 'cortex-m4f',
        },

        # mbed boards
        'mbed-lpc1768' : {
            'uvision' : 'LPC1768',
            'iar' : 'LPC1768',
            'coide' : 'LPC1768',
            'gcc' : 'cortex-m3',
        },

        # ST Disco boards
        'disco_f407vg' : {
            'coide' : 'STM32F407VG',
            'gcc' : 'cortex-m4',
        },
    }
``` 

This can be expressed in the yaml file, provided externally, and the pg just gets the board. This ticket is to start a discussion how it can be implemented so it scales. The initial idea was to have a common place, but probably would be better to have a repo with all these definitions, which can be easily pulled and used.

**Comment by matthewelse** [comment]
I think this would make the most sense as a repo called project_generator_definitions or something like that

**Comment by aethaniel** [comment]
+1
Indeed, if it is possible it would be great and separate process from generic and global data.


On 18 March 2015 19:42:44 CET, Matthew Else <notifications@github.com> wrote:
>I think this would make the most sense as a repo called
>project_generator_definitions or something like that
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/0xc0170/project_generator/issues/67#issuecomment-83116994

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by 0xc0170** [comment]
I believe MCU def should be also then make external, the only tool settings definitions would stay.

The one idea can be a github repository, which can be automatically pulled and parsed , to form a valid python dictionary. Or supplied a path for find this definitions locally, and use those. Let's look at options, and propose a simpleyaml file how it would look like lets say for uvision and how to pass it ot the generator

**Comment by 0xc0170** [comment]
An example of yaml definitions


```
board_definitions:
    frdm-k20d50m:
        uvision:
            - MK20DX128xxx5
        gcc:
            - cortex-m4
    frdm-kl25z:
        iar:
            - MKL25Z128xxx4
        gcc:
            - cortex-m0+

mcu_definitions:
    uvision:
        MK20DX128xxx5:
            TargetOption:
                Device:
                    - MK20DX128xxx5
                Vendor:
                     'Freescale Semiconductor',
                Cpu:
                    - IRAM(0x1FFFE000-0x1FFFFFFF) IRAM2(0x20000000-0x20001FFF) IROM(0x0-0x1FFFF) IROM2(0x10000000-0x10007FFF) CLOCK(12000000) CPUTYPE("Cortex-M4") ELITTLE
                FlashDriverDll:
                    - ULP2CM3(-O2510 -S0 -C0 -FO15 -FD20000000 -FC800 -FN2 -FF0MK_P128_50MHZ -FS00 -FL020000 -FF1MK_D32_50MHZ -FS110000000 -FL108000)
                DeviceId:
                    - 6206
                SFDFile:
                    - SFD\Freescale\Kinetis\MK20D5.sfr
```
